version: 0.1.0.{build}

os: unstable

configuration:
  - Debug
  - Release

environment:
  matrix:
  - VS_VERSION: 11
    VS_PLATFORM: win32
  - VS_VERSION: 11
    VS_PLATFORM: x64
  - VS_VERSION: 12
    VS_PLATFORM: win32
  - VS_VERSION: 12
    VS_PLATFORM: x64


install:
  - set QTDIR=C:\Qt\Qt5.3.2\5.3\mingw482_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin

build:
  - qmake ScreenFlow.pro
  - mingw32-make